[package]
name = "rpncalc"
version = "0.1.0"
authors = ["Tatsunori Shiomoto <ryuusyou3174@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
futures = "0.3.8"
rand = "0.7.3"
